#!/bin/sh
# Clean script for Clojure on Unix.
# Copyright (c) 2020 Michael Chen.
# Licensed under MIT

# Place clojure, build and clean at the root path of of a local Clojure repo.


root=$(dirname "$0");

rm -rf "$root/clojure.jar" "$root/apache-maven-3.6.3-bin.tar.gz" \
    "$root/apache-maven-3.6.3"