#!/bin/sh
# Clean script for Clojure on Unix.
# Copyright (c) 2020 Michael Chen.
# Licensed under MIT

# Place the script at the scripts/ subdirectory of of a local Clojure repo.

script_path="$(dirname $0)";
root="${script_path}/..";

rm -rf "$root/clojure.jar" "$root/apache-maven-3.6.3-bin.tar.gz" \
    "$root/apache-maven-3.6.3"