#!/bin/sh
# Wrapper for Clojure on Unix.
# Copyright (c) 2020 Michael Chen.
# Licensed under MIT

# Place the script at the root path of of a local Clojure repo.


# Check whether Java is available.
if ! command -v java -version 2>/dev/null 1>&2;
then
    echo "No Java on the system" >&2;
    exit 1;
fi

# Add `rlwrap` support if it is available.
if command -v rlwrap --version 2>/dev/null 1>&2;
then
    wrap=rlwrap
else
    wrap=""
fi

cwd="$(pwd)";
root=$(dirname "$0");

if [ "" = "$CLASSPATH" ];
then
    extra_classpath=":.";
else
    extra_classpath=":$CLASSPATH:.";
fi

if ! [ -f "$root/clojure.jar" ];
then
    echo "No compiled Clojure on the system" >&2;
    echo "Compile Clojure from scratch" >&2;
    
    "$root/scripts/clean";
    "$root/scripts/build";
    
    cd "$cwd";

    echo "Restart Clojures" >&2;
    exit 0;
fi

arg="$1";
if [ -z "$arg" ];
then
    # Run Clojure in interactive mode with optional `rlwrap` support.
    "$wrap" java -cp "$root/clojure.jar$extra_classpath" clojure.main "$@";
else
    # Run Clojure in batch mode.
    java -cp "$root/clojure.jar$extra_classpath" clojure.main "$@";
fi